source 'https://rubygems.org'
gem 'rails', '4.0.1'
gem 'pg'
gem 'jquery-rails'
gem 'haml'
gem 'bcrypt-ruby'
gem 'nokogiri'
gem 'simple_form'
gem 'squeel'
gem 'carrierwave'
gem 'fog'
gem 'rmagick'
gem 'remotipart'
gem 'unf'
#adding these for 4.0 update
gem 'protected_attributes'
gem 'actionpack-action_caching'
gem 'activerecord-session_store'
gem 'rails-observers'

gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'

group :development, :test do
  gem 'coffee-rails-source-maps'
  gem 'factory_girl_rails'
  gem 'guard-rspec'
  gem 'rb-fsevent'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'launchy'
  gem 'database_cleaner'
  gem 'pry-rails'
  gem 'pry-debugger'
  gem 'pry-stack_explorer'
  gem 'annotate'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
end
